// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require('request');

  require('shelljs/global');

  module.exports = function(grunt) {
    var changedFiles, onChange;
    grunt.registerTask("watchFiles", function() {
      return console.log("Watching files . . .");
    });
    changedFiles = Object.create(null);
    grunt.event.on("watch", function(action, filepath) {
      changedFiles[filepath] = action;
      return onChange();
    });
    return onChange = grunt.util._.debounce(function() {
      Object.keys(changedFiles).forEach(function(file) {
        var action, fileContent;
        action = changedFiles[file];
        if (action === "deleted") {
          return request.del({
            uri: "http://basedevmkp.vtexlocal.com.br",
            form: {
              filePath: file
            }
          });
        } else {
          fileContent = cat(file);
          console.log(fileContent);
          return request.put({
            uri: "http://basedevmkp.vtexlocal.com.br",
            body: fileContent,
            form: {
              filePath: file
            }
          }, function(error, response, body) {
            if (response.statusCode === 200) {
              return console.log('file saved');
            } else {
              console.log('error: ' + response.statusCode);
              return console.log(body);
            }
          });
        }
      });
      return changedFiles = Object.create(null);
    }, 300);
  };

}).call(this);
